/**
 * bust.js — 3D Bust Viewer (ES Module)
 *
 * Three.js GLTFLoader renderer for historical figure busts generated by BustAgent.
 * Exposes window.BustViewer for any non-module script that needs it.
 *
 * Integration:
 *   - Watches #step5 for becoming active via MutationObserver
 *   - Auto-loads bust if speech.bustGlbUrl is set (pre-generated demo assets)
 *   - Falls back to "Generate 3D Bust" button → calls /api/v1/sessions/{id}/bust/generate
 *   - Polls for completion, then loads the GLB via Three.js + GLTFLoader
 */

import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

// ── Bust Viewer Class ─────────────────────────────────────────────────────────

class BustViewerClass {
  constructor() {
    this._renderer  = null;
    this._scene     = null;
    this._camera    = null;
    this._controls  = null;
    this._animId    = null;
    this._resizeObs = null;
    this._ready     = false;
  }

  /**
   * Initialise (or re-initialise) the Three.js renderer onto a canvas element.
   * @param {HTMLCanvasElement} canvas
   */
  init(canvas) {
    if (this._ready) this.dispose();

    const parent = canvas.parentElement;
    const w = parent ? parent.clientWidth  : (canvas.clientWidth  || 300);
    const h = parent ? parent.clientHeight : (canvas.clientHeight || 300);

    // Renderer
    this._renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false });
    this._renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this._renderer.setSize(w, h, false);
    this._renderer.outputColorSpace  = THREE.SRGBColorSpace;
    this._renderer.toneMapping       = THREE.ACESFilmicToneMapping;
    this._renderer.toneMappingExposure = 1.2;
    this._renderer.shadowMap.enabled = true;
    this._renderer.shadowMap.type    = THREE.PCFSoftShadowMap;

    // Scene
    this._scene = new THREE.Scene();
    this._scene.background = new THREE.Color(0x0f0d20);
    this._scene.fog = new THREE.FogExp2(0x0f0d20, 0.12);

    // Camera
    this._camera = new THREE.PerspectiveCamera(38, w / h, 0.01, 50);
    this._camera.position.set(0, 0.15, 2.5);

    // ── Lighting — warm key + teal accent fill + soft rim ──
    this._scene.add(new THREE.AmbientLight(0xffeedd, 0.4));

    const key = new THREE.DirectionalLight(0xfff4e0, 1.4);
    key.position.set(1.5, 2.5, 2);
    key.castShadow              = true;
    key.shadow.mapSize.width    = 1024;
    key.shadow.mapSize.height   = 1024;
    key.shadow.camera.near      = 0.1;
    key.shadow.camera.far       = 20;
    this._scene.add(key);

    const fill = new THREE.DirectionalLight(0x3abfbf, 0.35); // teal accent
    fill.position.set(-2, 0.5, 1);
    this._scene.add(fill);

    const rim = new THREE.DirectionalLight(0xaaccff, 0.2);
    rim.position.set(0, -1, -3);
    this._scene.add(rim);

    // Controls
    this._controls = new OrbitControls(this._camera, canvas);
    this._controls.enableDamping   = true;
    this._controls.dampingFactor   = 0.06;
    this._controls.enablePan       = false;
    this._controls.minDistance     = 0.8;
    this._controls.maxDistance     = 6;
    this._controls.autoRotate      = true;
    this._controls.autoRotateSpeed = 1.0;
    this._controls.target.set(0, 0, 0);
    this._controls.update();

    // Responsive resize
    if (parent) {
      this._resizeObs = new ResizeObserver(() => {
        if (!this._renderer || !parent) return;
        const pw = parent.clientWidth;
        const ph = parent.clientHeight || 300;
        this._renderer.setSize(pw, ph, false);
        this._camera.aspect = pw / ph;
        this._camera.updateProjectionMatrix();
      });
      this._resizeObs.observe(parent);
    }

    this._ready = true;
    this._loop();
  }

  /**
   * Load a GLB file from a URL and display it in the viewer.
   * @param {string} glbUrl
   * @param {{ onProgress?: (pct:number)=>void, onLoad?: ()=>void, onError?: (err:Error)=>void }} callbacks
   */
  load(glbUrl, { onProgress, onLoad, onError } = {}) {
    if (!this._ready) return;

    // Clear any previously loaded bust model
    const toRemove = this._scene.children.filter(o => o.userData.bustModel);
    toRemove.forEach(o => {
      o.traverse(n => {
        if (n.isMesh) {
          n.geometry?.dispose();
          if (Array.isArray(n.material)) n.material.forEach(m => m.dispose());
          else n.material?.dispose();
        }
      });
      this._scene.remove(o);
    });

    const loader = new GLTFLoader();
    loader.load(
      glbUrl,
      (gltf) => {
        const model = gltf.scene;
        model.userData.bustModel = true;

        // Center model and scale to unit height
        const box    = new THREE.Box3().setFromObject(model);
        const center = box.getCenter(new THREE.Vector3());
        const size   = box.getSize(new THREE.Vector3());
        const scale  = 1.6 / Math.max(size.x, size.y, size.z);

        model.scale.setScalar(scale);
        model.position.copy(center.negate().multiplyScalar(scale));

        // Enable shadows
        model.traverse(n => {
          if (n.isMesh) {
            n.castShadow    = true;
            n.receiveShadow = true;
          }
        });

        this._scene.add(model);
        // Orbit around the vertical centre of the bust
        this._controls.target.set(0, size.y * scale * 0.05, 0);
        this._controls.update();

        if (onLoad) onLoad();
      },
      (xhr) => {
        if (onProgress && xhr.total) {
          onProgress(Math.round((xhr.loaded / xhr.total) * 100));
        }
      },
      (err) => {
        console.error("[BustViewer] GLB load error:", err);
        if (onError) onError(err);
      },
    );
  }

  /** Clean up Three.js resources. */
  dispose() {
    cancelAnimationFrame(this._animId);
    this._resizeObs?.disconnect();
    this._controls?.dispose();
    this._renderer?.dispose();
    this._ready    = false;
    this._renderer = this._scene = this._camera = this._controls = null;
  }

  _loop() {
    this._animId = requestAnimationFrame(() => this._loop());
    this._controls?.update();
    if (this._renderer && this._scene && this._camera) {
      this._renderer.render(this._scene, this._camera);
    }
  }
}

window.BustViewer = new BustViewerClass();

// ── DOM Integration ───────────────────────────────────────────────────────────

document.addEventListener("DOMContentLoaded", () => {
  const step5El    = document.getElementById("step5");
  const canvasEl   = document.getElementById("bustCanvas");
  const idleEl     = document.getElementById("bustIdle");
  const loadingEl  = document.getElementById("bustLoading");
  const errorEl    = document.getElementById("bustError");
  const genBtn     = document.getElementById("generateBustBtn");
  const retryBtn   = document.getElementById("retryBustBtn");
  const titleEl    = document.getElementById("bustFigureLabel");
  const progressEl = document.getElementById("bustProgress");
  const errorMsgEl = document.getElementById("bustErrorMsg");

  if (!step5El || !canvasEl) return; // Viewer elements not in DOM

  // ── Watch step 5 becoming active ──────────────────────────────────────────
  new MutationObserver(() => {
    if (step5El.classList.contains("active")) _onStep5Active();
  }).observe(step5El, { attributes: true, attributeFilter: ["class"] });

  // ── Button handlers ───────────────────────────────────────────────────────
  genBtn?.addEventListener("click", _handleGenerate);
  retryBtn?.addEventListener("click", _handleGenerate);

  // ── State helpers ─────────────────────────────────────────────────────────
  function _showState(s) {
    // s: "idle" | "loading" | "viewer" | "error"
    idleEl.hidden    = s !== "idle";
    loadingEl.hidden = s !== "loading";
    canvasEl.hidden  = s !== "viewer";
    errorEl.hidden   = s !== "error";
  }

  function _getSelectedSpeech() {
    const card = document.querySelector(".speech-card.selected");
    if (!card) return null;
    return (window.SPEECHES_DB || []).find(s => s.id === card.dataset.id) ?? null;
  }

  // ── Step 5 activation ─────────────────────────────────────────────────────
  function _onStep5Active() {
    const speech = _getSelectedSpeech();
    if (titleEl && speech) titleEl.textContent = speech.figure ?? "Figure";

    if (speech?.bustGlbUrl) {
      // Pre-generated static asset — load immediately
      _loadGlb(speech.bustGlbUrl);
    } else {
      _showState("idle");
    }
  }

  function _loadGlb(url) {
    _showState("loading");
    if (progressEl) progressEl.style.width = "0%";

    window.BustViewer.init(canvasEl);
    window.BustViewer.load(url, {
      onProgress: (pct) => {
        if (progressEl) progressEl.style.width = pct + "%";
      },
      onLoad: () => _showState("viewer"),
      onError: () => {
        if (errorMsgEl) errorMsgEl.textContent = "Failed to load GLB file.";
        _showState("error");
      },
    });
  }

  // ── Generate button ────────────────────────────────────────────────────────
  async function _handleGenerate() {
    const speech    = _getSelectedSpeech();
    const sessionId = window._HISTORYLIVE_SESSION_ID ?? null;

    _showState("loading");
    if (progressEl) progressEl.style.width = "8%";

    try {
      if (sessionId) {
        await _generateViaApi(sessionId, speech);
      } else {
        // Demo mode — no live backend session
        await _simulateGeneration();
      }
    } catch (err) {
      console.warn("[BustViewer] generate failed:", err);
      if (errorMsgEl) errorMsgEl.textContent = err.message ?? "Generation failed.";
      _showState("error");
    }
  }

  async function _generateViaApi(sessionId, speech) {
    const body = {};
    if (speech?.figure)                   body.figure_name = speech.figure;
    if (speech?.bustPhysicalDescription)  body.physical_description = speech.bustPhysicalDescription;

    const resp = await fetch(`/api/v1/sessions/${encodeURIComponent(sessionId)}/bust/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify(body),
    });
    if (!resp.ok) throw new Error(`Server error ${resp.status}`);

    // Poll for a ready bust
    const glbUrl = await _pollBustReady(sessionId);
    _loadGlb(glbUrl);
  }

  async function _pollBustReady(sessionId) {
    const MAX  = 72;   // 72 × 5 s = 6 min max
    const TICK = 5000;
    for (let i = 0; i < MAX; i++) {
      await new Promise(r => setTimeout(r, TICK));
      if (progressEl) progressEl.style.width = Math.min(10 + i * 1.1, 88) + "%";

      const r = await fetch(`/api/v1/sessions/${encodeURIComponent(sessionId)}/bust`, {
        credentials: "same-origin",
      });
      if (!r.ok) continue;

      const busts = await r.json();
      const ready = busts.find(b => b.status === "ready" && b.glb_url);
      if (ready) {
        if (progressEl) progressEl.style.width = "100%";
        return ready.glb_url;
      }
    }
    throw new Error("Bust generation timed out. Try again later.");
  }

  async function _simulateGeneration() {
    // Demo mode: no backend. Animate the progress bar then show a message.
    const steps = [15, 30, 48, 65, 82, 95];
    for (const pct of steps) {
      await new Promise(r => setTimeout(r, 550));
      if (progressEl) progressEl.style.width = pct + "%";
    }
    // In a real demo, set speech.bustGlbUrl to a pre-generated static GLB
    // and this path will never be reached.
    if (errorMsgEl) {
      errorMsgEl.textContent =
        "Demo mode: no pre-generated bust for this figure. " +
        "Run BustAgent to generate a GLB, then set bustGlbUrl in speeches.js.";
    }
    _showState("error");
  }
});
