/**
 * speeches.js — Curated historical speech database
 * Each entry contains all data needed to auto-fill the research form.
 *
 * bustGlbUrl: path/URL to a pre-generated GLB bust (from BustAgent).
 *   Set to a real URL after running `POST /api/v1/sessions/{id}/bust/generate`
 *   for each figure. null = "Generate 3D Bust" button shown instead.
 * bustPhysicalDescription: fed to the portrait prompt in BustAgent.
 */

window.SPEECHES_DB = [
  {
    id: "gettysburg-1863",
    figure: "Abraham Lincoln",
    speech: "Gettysburg Address",
    bustGlbUrl: null,
    bustPhysicalDescription: "tall, bearded, frock coat, stovepipe hat, gaunt but dignified features",
    era: "modern",
    year: 1863,
    emoji: "🎩",
    description: "Delivered at the dedication of the Soldiers' National Cemetery during the Civil War.",
    research: {
      speakerName: "Abraham Lincoln",
      speechTitle: "Gettysburg Address",
      speechVersion: "primary",
      speechVariations: "Fifth and final 'Bliss' copy is considered the authoritative text; delivery may have differed slightly from text.",
      speechLanguage: "English",
      speechDialect: "19th-century American English, Illinois frontier accent",
      speechTranscript: `Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.\n\nNow we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.\n\n...That this nation, under God, shall have a new birth of freedom — and that government of the people, by the people, for the people, shall not perish from the earth.`,
      locationCity: "Gettysburg",
      locationState: "Pennsylvania",
      locationCountry: "United States",
      speechDate: "November 19, 1863",
      timePeriod: "American Civil War, 1860s",
      settingType: "outdoor",
      buildingName: "",
      roomType: "",
      roomNotes: "Open field, temporary wooden platform at Soldiers' National Cemetery",
      audienceType: "mixed",
      audienceSize: "~15,000 attendees",
      audienceNotes: "Mix of Union soldiers, civilians, politicians in mourning dress. Overcast mid-afternoon sky.",
      speakerPosition: "podium",
      micType: "none",
      speakerAttire: "Black frock coat, stovepipe hat, white shirt, dark bow tie. Holding remarks on paper.",
      speakerNotes: "Spoke briefly (~2 minutes). Solemn, measured delivery. Applause was reportedly scattered at first.",
      accuracyNotes: "No electric lighting. No microphones. 35-star US flag. Temporary wooden platform. Edward Everett spoke for ~2 hours before Lincoln.",
    }
  },
  {
    id: "ihaveadream-1963",
    figure: "Dr. Martin Luther King Jr.",
    speech: "I Have a Dream",
    bustGlbUrl: null,
    bustPhysicalDescription: "dark suit, white dress shirt, dark tie, 1963, dignified and powerful bearing",
    era: "contemporary",
    year: 1963,
    emoji: "✊",
    description: "Landmark civil rights speech delivered at the March on Washington for Jobs and Freedom.",
    research: {
      speakerName: "Dr. Martin Luther King Jr.",
      speechTitle: "I Have a Dream",
      speechVersion: "primary",
      speechVariations: "The famous 'dream' section was improvised by King; it was not in his prepared text.",
      speechLanguage: "English",
      speechDialect: "Southern American English, Atlanta, Georgia accent",
      speechTranscript: `I am happy to join with you today in what will go down in history as the greatest demonstration for freedom in the history of our nation.\n\n...I have a dream that one day this nation will rise up and live out the true meaning of its creed: "We hold these truths to be self-evident, that all men are created equal."\n\nI have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.`,
      locationCity: "Washington",
      locationState: "D.C.",
      locationCountry: "United States",
      speechDate: "August 28, 1963",
      timePeriod: "American Civil Rights Movement, 1960s",
      settingType: "outdoor",
      buildingName: "Lincoln Memorial steps",
      roomType: "",
      roomNotes: "Steps of Lincoln Memorial, facing the National Mall toward the Washington Monument",
      audienceType: "standing",
      audienceSize: "~250,000 marchers",
      audienceNotes: "Massive, jubilant, racially diverse crowd. Hot summer afternoon. Many carried signs.",
      speakerPosition: "podium",
      micType: "dynamic",
      speakerAttire: "Dark charcoal suit, white dress shirt, dark tie.",
      speakerNotes: "Powerful, preacher-style cadence. Built to crescendo. Voice carried passion and urgency.",
      accuracyNotes: "Multiple dynamic microphones at podium. CBS, NBC, ABC broadcast live. Hot August afternoon, sunny. Crowd extended nearly a mile down the reflecting pool.",
    }
  },
  {
    id: "hammurabi-code",
    figure: "Hammurabi",
    speech: "Prologue to the Code of Hammurabi",
    bustGlbUrl: null,
    bustPhysicalDescription: "Babylonian king, tall horned crown, long black beard, royal robes, rod-and-ring symbol",
    era: "ancient",
    year: -1754,
    emoji: "⚖️",
    description: "Royal proclamation establishing the foundational laws of the Babylonian Empire.",
    research: {
      speakerName: "Hammurabi, King of Babylon",
      speechTitle: "Prologue to the Code of Hammurabi",
      speechVersion: "primary",
      speechVariations: "Only written version survives; oral proclamation would have been to court officials and scribes.",
      speechLanguage: "Akkadian",
      speechDialect: "Old Babylonian dialect of Akkadian",
      speechTranscript: `When the lofty Anu, king of the Anunnaki, and Enlil, lord of heaven and earth, who determines the destinies of the land, committed the rule of all mankind to Marduk, the chief son of Ea...\n\nAt that time, Anu and Enlil named me to promote the welfare of the people, me, Hammurabi, the devout, god-fearing prince, to cause justice to prevail in the land, to destroy the wicked and the evil, to prevent the strong from oppressing the weak...`,
      locationCity: "Babylon",
      locationState: "Mesopotamia",
      locationCountry: "Babylonian Empire (modern Iraq)",
      speechDate: "c. 1754 BCE",
      timePeriod: "Old Babylonian Period, ~1800–1750 BCE",
      settingType: "indoor",
      buildingName: "Temple of Marduk (Esagila) or Royal Palace, Babylon",
      roomType: "hall",
      roomNotes: "Grand throne room or temple hall, stone columns, oil lamps, richly decorated with lapis lazuli and gold.",
      audienceType: "chairs",
      audienceSize: "Court officials, scribes, priests — perhaps 50–200 persons",
      audienceNotes: "Babylonian court officials in fine robes. Scribes with clay tablets. Priests and military commanders.",
      speakerPosition: "elevated",
      micType: "none",
      speakerAttire: "Royal Babylonian robes, tall horned crown, long black beard, holding a rod-and-ring symbol of authority.",
      speakerNotes: "Formal, ceremonial delivery. Would have been translated and read by herald scribes.",
      accuracyNotes: "Oil lamp lighting only. Stone-carved stele. No written records of the oral delivery — reconstruct from physical and cultural context. Cuneiform tablets for scribes.",
    }
  },
  {
    id: "sojourner-truth-1851",
    figure: "Sojourner Truth",
    speech: "Ain't I a Woman?",
    bustGlbUrl: null,
    bustPhysicalDescription: "tall commanding presence, plain grey Quaker-style dress, white cap, 1851",
    era: "modern",
    year: 1851,
    emoji: "🌟",
    description: "Extemporaneous speech at the Women's Rights Convention in Akron, Ohio.",
    research: {
      speakerName: "Sojourner Truth (born Isabella Baumfree)",
      speechTitle: "Ain't I a Woman?",
      speechVersion: "primary",
      speechVariations: "Two transcriptions exist: Marius Robinson's 1851 version and Frances Gage's 1863 recollection (with added Southern dialect that may not be accurate — Truth was from New York).",
      speechLanguage: "English",
      speechDialect: "Northern American English (New York/Ohio), abolitionist preacher style",
      speechTranscript: `Well, children, where there is so much racket there must be something out of kilter. I think that 'twixt the negroes of the South and the women at the North, all talking about rights, the white men will be in a fix pretty soon.\n\nThat man over there says that women need to be helped into carriages, and lifted over ditches, and to have the best place everywhere. Nobody ever helps me into carriages, or over mud-puddles, or gives me any best place! And ain't I a woman?`,
      locationCity: "Akron",
      locationState: "Ohio",
      locationCountry: "United States",
      speechDate: "May 29, 1851",
      timePeriod: "Antebellum America, 1850s",
      settingType: "indoor",
      buildingName: "Old Stone Church (Stone Church), Akron",
      roomType: "church",
      roomNotes: "Church sanctuary converted for convention use. Wooden pews, natural light from windows.",
      audienceType: "built-in",
      audienceSize: "Several hundred convention attendees",
      audienceNotes: "Women's rights activists, abolitionists, some hostile observers. Some men in balcony. Varied reception.",
      speakerPosition: "podium",
      micType: "none",
      speakerAttire: "Plain grey Quaker-style dress, white neck cloth, white cap. Tall, commanding presence (nearly 6 feet).",
      speakerNotes: "Powerful extemporaneous delivery. Deep, resonant voice. Known for humor and directness.",
      accuracyNotes: "Natural light only. No microphones. Candles or oil lamps for evening. 1851 — no photography of event.",
    }
  },
  {
    id: "winston-churchill-finest-hour",
    figure: "Winston Churchill",
    speech: "Their Finest Hour",
    bustGlbUrl: null,
    bustPhysicalDescription: "stocky, dark three-piece suit, white pocket square, bow tie, stern wartime expression, 1940",
    era: "modern",
    year: 1940,
    emoji: "🎖️",
    description: "Radio address to the nation after France's fall, rallying Britain against Nazi Germany.",
    research: {
      speakerName: "Winston Leonard Spencer Churchill, Prime Minister",
      speechTitle: "Their Finest Hour",
      speechVersion: "primary",
      speechVariations: "Delivered first to House of Commons, then broadcast on BBC radio that evening.",
      speechLanguage: "English",
      speechDialect: "Received Pronunciation, upper-class British, Edwardian cadence",
      speechTranscript: `What General Weygand called the Battle of France is over. I expect that the Battle of Britain is about to begin...\n\nLet us therefore brace ourselves to our duties, and so bear ourselves that, if the British Empire and its Commonwealth last for a thousand years, men will still say, "This was their finest hour."`,
      locationCity: "London",
      locationState: "England",
      locationCountry: "United Kingdom",
      speechDate: "June 18, 1940",
      timePeriod: "World War II, Battle of Britain",
      settingType: "indoor",
      buildingName: "BBC Broadcasting House / House of Commons, Westminster",
      roomType: "chamber",
      roomNotes: "Wood-panelled chamber with green leather benches (Commons). BBC studio small, intimate, ribbon mic on table.",
      audienceType: "built-in",
      audienceSize: "House of Commons (~600 MPs); radio audience of millions",
      audienceNotes: "MPs in formal suits, wartime tension palpable. BBC broadcast reached millions of British homes.",
      speakerPosition: "podium",
      micType: "ribbon",
      speakerAttire: "Dark three-piece suit, white pocket square, polka-dot bow tie, cigar nearby but not during broadcast.",
      speakerNotes: "Deliberate, theatrical pacing. Famous for pauses. Wrote and rewrote speeches obsessively.",
      accuracyNotes: "Ribbon microphone at Commons dispatch box. BBC broadcast used separate ribbon mic in studio. Electric lighting inside. Wartime blackout curtains on windows.",
    }
  },
  {
    id: "pericles-funeral-oration",
    figure: "Pericles",
    speech: "Funeral Oration",
    bustGlbUrl: null,
    bustPhysicalDescription: "Classical Athenian general, white chiton, olive wreath, strong jaw, bearded, commanding presence",
    era: "ancient",
    year: -431,
    emoji: "🏛️",
    description: "Eulogy for Athenian soldiers killed in the first year of the Peloponnesian War.",
    research: {
      speakerName: "Pericles, Strategos of Athens",
      speechTitle: "Funeral Oration (Epitaphios Logos)",
      speechVersion: "primary",
      speechVariations: "Known only through Thucydides' reconstruction in 'History of the Peloponnesian War' — likely a paraphrased approximation, not verbatim.",
      speechLanguage: "Ancient Greek",
      speechDialect: "Classical Attic Greek",
      speechTranscript: `Our constitution does not copy the laws of neighbouring states; we are rather a pattern to others than imitators ourselves. Its administration favours the many instead of the few; this is why it is called a democracy...\n\nFix your eyes on the greatness of Athens as you have it before you day by day, fall in love with her, and when you feel her great, remember that this greatness was won by men with courage, with knowledge of their duty, and with a sense of honour in action.`,
      locationCity: "Athens",
      locationState: "Attica",
      locationCountry: "Ancient Greece",
      speechDate: "Winter, 431–430 BCE",
      timePeriod: "Classical Greece, Peloponnesian War",
      settingType: "outdoor",
      buildingName: "Kerameikos (Ceramicus) Cemetery, outside the Dipylon Gate",
      roomType: "",
      roomNotes: "Public burial grounds. Temporary wooden platform (bema) erected for speaker. Cypress trees, stone tombs.",
      audienceType: "standing",
      audienceSize: "Thousands of Athenian citizens, soldiers' families",
      audienceNotes: "Grieving families, soldiers, citizens of Athens. Women wailed in ritual mourning. Solemn procession prior.",
      speakerPosition: "elevated",
      micType: "none",
      speakerAttire: "White chiton, himation draped over shoulder, wreath of laurel or olive. Bareheaded.",
      speakerNotes: "Projected without amplification. Classical Greek rhetorical style (logos, ethos, pathos). Commanding presence.",
      accuracyNotes: "No amplification. Daylight outdoor setting. Cypress and plane trees. Ceramic vessels for ashes. No photography, reconstruct from vase paintings and contemporary accounts.",
    }
  },
  {
    id: "jfk-moon-speech",
    figure: "John F. Kennedy",
    speech: "We Choose to Go to the Moon",
    bustGlbUrl: null,
    bustPhysicalDescription: "dark suit, white shirt, dark tie, youthful tanned face, 1962, charismatic",
    era: "contemporary",
    year: 1962,
    emoji: "🚀",
    description: "Historic speech at Rice University challenging America to land on the Moon.",
    research: {
      speakerName: "President John F. Kennedy",
      speechTitle: "We Choose to Go to the Moon (Moon Speech)",
      speechVersion: "primary",
      speechVariations: "One main delivery. Written text and final delivery match closely.",
      speechLanguage: "English",
      speechDialect: "Boston Brahmin accent, New England American English",
      speechTranscript: `We choose to go to the Moon. We choose to go to the Moon in this decade and do the other things, not because they are easy, but because they are hard...\n\nWe shall not see space filled with weapons of mass destruction, but with instruments of knowledge and understanding.`,
      locationCity: "Houston",
      locationState: "Texas",
      locationCountry: "United States",
      speechDate: "September 12, 1962",
      timePeriod: "Space Race, Cold War era, 1960s",
      settingType: "outdoor",
      buildingName: "Rice University Stadium",
      roomType: "auditorium",
      roomNotes: "Open-air stadium on the Rice University campus. Sunny Sept. afternoon (35,000 seats).",
      audienceType: "built-in",
      audienceSize: "~35,000 people",
      audienceNotes: "University students, faculty, press corps, government officials. Hot Houston afternoon.",
      speakerPosition: "podium",
      micType: "condenser",
      speakerAttire: "Crisp white shirt, dark tie, dark suit jacket. Tanned, youthful appearance.",
      speakerNotes: "Energetic, optimistic cadence. Strong eye contact with crowd. Trademark Boston accent.",
      accuracyNotes: "Multiple condenser mics at podium. Full press corps with TV cameras. The podium had the presidential seal. Sunny outdoor afternoon.",
    }
  },
  {
    id: "nelson-mandela-release",
    figure: "Nelson Mandela",
    speech: "Release from Prison Speech",
    bustGlbUrl: null,
    bustPhysicalDescription: "dark suit, white shirt, tie, dignified grey-haired elder, fist raised, 1990",
    era: "contemporary",
    year: 1990,
    emoji: "✌️",
    description: "First public address after 27 years of imprisonment, delivered at Cape Town City Hall.",
    research: {
      speakerName: "Nelson Rolihlahla Mandela",
      speechTitle: "Release from Prison Address",
      speechVersion: "primary",
      speechVariations: "Single delivery from Cape Town City Hall balcony.",
      speechLanguage: "English",
      speechDialect: "South African English (Xhosa mother tongue clearly present in cadence)",
      speechTranscript: `Friends, comrades and fellow South Africans — I greet you all in the name of peace, democracy and freedom for all!\n\nI stand here before you not as a prophet but as a humble servant of you, the people. Your tireless and heroic sacrifices have made it possible for me to be here today. I therefore place the remaining years of my life in your hands.`,
      locationCity: "Cape Town",
      locationState: "Western Cape",
      locationCountry: "South Africa",
      speechDate: "February 11, 1990",
      timePeriod: "End of Apartheid era, 1990",
      settingType: "outdoor",
      buildingName: "Cape Town City Hall",
      roomType: "hall",
      roomNotes: "Balcony overlooking the Grand Parade — a massive open square filled with the crowd below.",
      audienceType: "standing",
      audienceSize: "~100,000 in the Grand Parade",
      audienceNotes: "Jubilant crowd waving ANC flags, singing. Some pushing and crushing at the front. Evening light.",
      speakerPosition: "podium",
      micType: "dynamic",
      speakerAttire: "Dark suit, white shirt, tie. Fist raised in ANC salute.",
      speakerNotes: "Calm and measured despite 27-year imprisonment. Reading from prepared notes. Greeted with massive roar.",
      accuracyNotes: "Handheld and podium dynamic mics. Evening, floodlights. Major TV broadcast worldwide. 1990 technology: shoulder-mounted cameras.",
    }
  }
];
